/* Auto-generated by tools/gen_fonts.py — DO NOT EDIT. */
#pragma once
#include "lvgl.h"

LV_FONT_DECLARE(bahn_160);
LV_FONT_DECLARE(bahn_72);
LV_FONT_DECLARE(bahn_48);
LV_FONT_DECLARE(bahn_36);
LV_FONT_DECLARE(bahn_28);
LV_FONT_DECLARE(bahn_20);
LV_FONT_DECLARE(bahn_16);
LV_FONT_DECLARE(bahn_14);
