#!/usr/bin/env python3
"""Generate LVGL v9 fmt_txt fonts (bpp4, plain) from Bahnschrift.

Rasterizes with Pillow and emits C files matching the structure of LVGL's
built-in fonts (see lv_font_montserrat_14.c). Bahnschrift is a variable
font shipped with Windows 10+; we pin wght=700 wdth=100 to match the HTML
prototype's `font-weight: 700` Bahnschrift rendering.

Run:  python tools/gen_fonts.py       (from firmware/)
Deps: pip install pillow
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = r"C:\Windows\Fonts\bahnschrift.ttf"
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "fonts")

ALNUM = "".join(chr(c) for c in range(0x20, 0x7B)) + "°"  # space..z + degree

# (name, px, charset)
FONTS = [
    ("bahn_160", 160, "-0123456789N"),
    ("bahn_72",  72,  "0123456789"),
    ("bahn_48",  48,  "-.0123456789"),
    ("bahn_36",  36,  "%-.0123456789"),
    ("bahn_28",  28,  ALNUM),
    ("bahn_20",  20,  ALNUM),
    ("bahn_16",  16,  ALNUM),
    ("bahn_14",  14,  ALNUM),
]


def load_font(px):
    f = ImageFont.truetype(FONT_PATH, px)
    try:
        f.set_variation_by_axes([700, 100])  # wght, wdth
    except Exception as e:
        print(f"  (variation not applied: {e})")
    return f


def render_glyph(font, ch, ascent):
    """Return (bitmap rows of 0..255, box_w, box_h, ofs_x, ofs_y, adv_w16)."""
    adv = font.getlength(ch)
    pad = 32
    W = int(adv) + pad * 2 + 8
    H = ascent + pad * 2 + 64
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    d.text((pad, pad), ch, font=font, fill=255)  # anchor 'la': baseline = pad+ascent
    bbox = img.getbbox()
    if bbox is None:  # space
        return [], 0, 0, 0, 0, round(adv * 16)
    x0, y0, x1, y1 = bbox
    crop = img.crop(bbox)
    rows = list(crop.getdata())
    box_w, box_h = x1 - x0, y1 - y0
    ofs_x = x0 - pad
    baseline_y = pad + ascent
    ofs_y = baseline_y - y1          # bottom of bbox relative to baseline
    return rows, box_w, box_h, ofs_x, ofs_y, round(adv * 16)


def pack_bpp4(pixels):
    """Continuous nibble stream, row-major, no row padding (LVGL plain bpp4)."""
    out = bytearray()
    hi = None
    for p in pixels:
        n = p >> 4
        if hi is None:
            hi = n
        else:
            out.append((hi << 4) | n)
            hi = None
    if hi is not None:
        out.append(hi << 4)
    return bytes(out)


def contiguous_ranges(codes):
    codes = sorted(codes)
    ranges = []
    start = prev = codes[0]
    for c in codes[1:]:
        if c == prev + 1:
            prev = c
            continue
        ranges.append((start, prev))
        start = prev = c
    ranges.append((start, prev))
    return ranges


def emit_font(name, px, charset):
    font = load_font(px)
    ascent, descent = font.getmetrics()
    codes = sorted(set(ord(c) for c in charset))

    glyphs = []      # (code, dsc fields, packed bytes)
    bitmap = bytearray()
    dscs = ["    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */"]
    for code in codes:
        rows, bw, bh, ox, oy, adv = render_glyph(font, chr(code), ascent)
        idx = len(bitmap)
        bitmap += pack_bpp4(rows)
        dscs.append(f"    {{.bitmap_index = {idx}, .adv_w = {adv}, .box_w = {bw}, "
                    f".box_h = {bh}, .ofs_x = {ox}, .ofs_y = {oy}}} /* U+{code:04X} */")
        glyphs.append(code)

    # cmaps: FORMAT0_TINY per contiguous range; glyph ids follow sorted order
    cmaps = []
    gid = 1
    for (a, b) in contiguous_ranges(codes):
        n = b - a + 1
        cmaps.append(
            "    {\n"
            f"        .range_start = {a}, .range_length = {n}, .glyph_id_start = {gid},\n"
            "        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,\n"
            "        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY\n"
            "    }")
        gid += n

    hexdump = []
    for i in range(0, len(bitmap), 16):
        hexdump.append("    " + ", ".join(f"0x{b:02x}" for b in bitmap[i:i + 16]) + ",")

    c = f"""/* Auto-generated by tools/gen_fonts.py — DO NOT EDIT.
 * Bahnschrift wght=700 wdth=100, {px} px, bpp 4, charset: {len(codes)} glyphs */
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{chr(10).join(hexdump)}
}};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{("," + chr(10)).join(dscs)}
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
{("," + chr(10)).join(cmaps)}
}};

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = {len(cmaps)},
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
}};

const lv_font_t {name} = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {ascent + descent},
    .base_line = {descent},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -2,
    .underline_thickness = 1,
    .dsc = &font_dsc,
}};
"""
    path = os.path.join(OUT_DIR, f"{name}.c")
    with open(path, "w", newline="\n") as fh:
        fh.write(c)
    print(f"  {name}.c: {len(codes)} glyphs, {len(bitmap)} bytes bitmap")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, px, charset in FONTS:
        print(f"{name} ({px}px)…")
        emit_font(name, px, charset)

    decls = "\n".join(f"LV_FONT_DECLARE({n});" for n, _, _ in FONTS)
    with open(os.path.join(OUT_DIR, "fonts.h"), "w", newline="\n") as fh:
        fh.write("/* Auto-generated by tools/gen_fonts.py — DO NOT EDIT. */\n"
                 "#pragma once\n#include \"lvgl.h\"\n\n" + decls + "\n")
    print("fonts.h written")


if __name__ == "__main__":
    sys.exit(main())
